### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by special** [s-rah/go-ricochet#18]
After the changes in #17, I started thinking about what I'd like a Go protocol API to actually look like. It got a bit out of hand.

I've written out some of the problems I've noticed for ricochet-go, along with a mostly-complete definition of an API that solves those problems with some other random ideas thrown in. I'm not 100% convinced that this is the right direction to go, and it very well may be over-engineered, but:

https://gist.github.com/special/5f19156dd76a7fb63a1135891a6a0521

All thoughts welcome. I don't plan to start writing code on this right away, and I'd like to make sure the approach seems good before putting more work into it.

**Comment by s-rah** [comment]
Awesome! Thanks for putting this together.

Lot's to unpack here, and probably, not going to get it all on the first go - but we've got to start somewhere. I'm going to use this issue to go through the future design stuff - I'll probably pull in #17 tomorrow, once I look at it again with fresh eyes, but overall I think it's going in the right direction.

> A minimal set of callbacks that build up the same layers as the protocol itself

+1
> Extensible with new channel types or behavior at the application level

+1
> We should be able to add new interfaces without breaking existing code

+1
> Applications shouldn't need to juggle protocol internals like channel IDs

+1
> Blocking APIs for authentication

+1
> Allow applications to change the handler of a connection as it moves between strictly distinct states (unauth -> unknown -> known)

+1
> Safe pattern for acting on a connection/channel from other goroutines

+1. go channels should be the base of  mechanism.


OK, onto specifics:

I like most of the proposed API outlines, I think it's pretty much where my mind has been wandering in regards to #15 

I would suggest a few things:

* Can we get rid of the ugly switch statement in `AutoConnectionHandler? - It would be more awesome to have Channel Handler register() with ACH and then we can simply map based on the type - this would make channel types much more pluggable - and then applications don't need to override the behaviour, they can simply plug in new channel handlers. This has been in my head for a while.

* On Originating messages & thread safety - Maybe we are on the same page, but I will double check anyway - Do you have an objection to serializing through go channels?

I think ideally that calls on OpenConnection should send messages to the main Process go routine through channels, and the UI should listen to messages via it's implemented interfaces outlined in the doc.

This means that UI triggered events will be potentially queued behind other events waiting their turn in that connections process loop (i.e. packet receives) but practically that shouldn't make a difference, and there are mechanisms for enforcing priority if we wanted to do that.

But if I am reading right you have an objection to this approach? It seems the two patterns you have proposed would both block the process loop in some way? The only ways I can see this implemented are priority channel based as above, or detecting the presence of some kind of lock and calling the desired function.

I currently don't see what benefit the latter provides over the channel based approach, maybe I'm missing something - I don't believe it's any more reliable than a priority go channel implementation - since you still have to wait for the loop to come around before the mutex locks.

That's all I have for now, I will revisit this tomorrow, as well as the PR - but I really like the direction this is going.

**Comment by special** [comment]
Another thought: should we enforce that all channels are closed when Break()ing out of a Process() call? That might restrict some unforeseen uses, but it would guarantee that switching handlers is a strict break in functionality.

> Can we get rid of the ugly switch statement in `AutoConnectionHandler? - It would be more awesome to have Channel Handler register() with ACH and then we can simply map based on the type - this would make channel types much more pluggable - and then applications don't need to override the behaviour, they can simply plug in new channel handlers. This has been in my head for a while.

Yes, definitely.

Technically, we could get rid of ConnectionHandler entirely, and have Process() implement the AutoConnectionHandler behavior with whatever interface{} it's given. The Ready and Closed callbacks are basically redundant, because entering Process() is application-controlled.

That would break the layering a bit. Another concern is that it's more difficult to override for custom channel open behavior -- like changing the rules for when certain channel types are allowed. That could be countered by adding an optional ChannelApprover interface, I suppose. 

> I think ideally that calls on OpenConnection should send messages to the main Process go routine through channels, and the UI should listen to messages via it's implemented interfaces outlined in the doc.

Yes, this is what I have in mind, _but_ the question is what those "messages" actually are.

Imagine if we sent fully-formed packets over a gochannel for the `Process()` loop to write out. This is obviously flawed: you have no safe way to get the channel id or channel-specific state, no guarantee that the channel you're sending to is still open at write-time, and it gets more complicated if you conditionally need to open a new channel.

We could serialize at a slightly higher level, like "send this packet to this channel", but most of those problems aren't solved. Any time that state can change while building your message or before it's queued up to the socket, there will be problems. I'll go into more detail below.

> This means that UI triggered events will be potentially queued behind other events waiting their turn in that connections process loop (i.e. packet receives) but practically that shouldn't make a difference, and there are mechanisms for enforcing priority if we wanted to do that.

Agreed, that shouldn't make a difference.

> But if I am reading right you have an objection to this approach? It seems the two patterns you have proposed would both block the process loop in some way? The only ways I can see this implemented are priority channel based as above, or detecting the presence of some kind of lock and calling the desired function.

Yes, blocking the process loop is exactly the point. I want to make sure that only one goroutine is acting on connection state. Normally - for all inbound messages, socket events, and calls to handlers - this will be the Process() goroutine. Sometimes we have another goroutine that wants to execute an operation like:

```go
    chat, _ := EnsureChatChannel(oc)
    chat.SendMessage("hello world")
```

This is unreliable if connection state can change between calls to `EnsureChatChannel` and `SendMessage`, so an internal lock isn't sufficient. We could build a higher-level API that serializes this into one operation over a gochannel or locks around it, but we'll end up building a _lot_ of those, for every necessary atomic operation you might want to do. Not an option.

So the problem to solve is: how do we guarantee that the neither the `Process()` goroutine or any other goroutine will change state during this operation? The two answers I gave are: we use a connection-wide mutex, or we make sure all state changes take place on the Process() goroutine.

The mutex solution is pretty obvious, but the closures approach is interesting and it's actually implemented entirely on gochannels.

```go
oc.Do(func() error {
    chat, _ := EnsureChatChannel(oc)
    return chat.SendMessage("hello world")
})
```

So, the goal is that the closure given to `Do()` will be executed _within_ the `Process()` routine, and Do is blocked until it returns. We know the operation is carried out atomically because all changes happen within the Process routine. The implementation is, paraphrased:

```go
type operation struct {
    Run func() error
    Return chan error
} 
// ...
operationsChannel := make(chan operation)

func Do(f func() error) error {
    result := make(chan error)
    operationsChannel <- operation{Run: f, Return: result}
    return <-result
}
```

`Process()` needs to be refactored too, but that was already necessary for other changes. It becomes a `select{}` over operationsChannel, a channel triggered by `Break()`, and a channel for inbound packets. It will also need to start an internal goroutine that blocks on reading the socket and sends packets into Process, but that's ok. We needed these kind of changes to make Break etc possible already.

Does that make sense? Do you have any alternative ideas? Do you want me to stop writing huge walls of text? ;)

**Comment by s-rah** [comment]
> Sometimes we have another goroutine that wants to execute an operation like:

    chat, _ := EnsureChatChannel(oc)
    chat.SendMessage("hello world")
> This is unreliable if connection state can change between calls to EnsureChatChannel and SendMessage, so an internal lock isn't sufficient. We could build a higher-level API that serializes this into one operation over a gochannel or locks around it, but we'll end up building a lot of those, for every necessary atomic operation you might want to do. Not an option.

Ah! Yes that makes sense now!
